export const englishSiteCopy = {
  nav: {
    why: 'Why Axis One',
    system: 'System',
    exposure: 'Decision exposure',
    trust: 'Trust',
    deployment: 'Deployment',
    frame: 'Frame a decision',
    menu: 'Menu',
    navigation: 'Navigation',
    close: 'Close navigation menu',
    skip: 'Skip to main content',
  },
  page: {
    eyebrow: 'Capital governance infrastructure',
  },
  footer: {
    explore: 'Explore',
    company: 'Company',
    home: 'Home',
    fullExposure: 'Full exposure model',
    founder: 'Founder',
    email: 'Enquiries',
    contact: 'Contact Axis One',
    kicker: 'Capital governance infrastructure',
    title: 'Capital, governed by execution.',
    body: 'Axis One connects committed capital to verified milestones, attributable evidence and controlled decision states.',
    operatingCompany: 'Operating company',
    nonCustodial: 'Non-custodial by design',
    boundary: 'Axis One does not hold, transfer, manage or guarantee client capital. Any transfer remains with an appropriately authorised external financial provider.',
    rights: 'All rights reserved.',
  },
} as const;
